# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ dev ]
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'maven'

    - name: Prepare artifacts
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        timedatectl status
        echo "BUILD_VERSION_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -U -B -T 1C clean package  -Dmaven.test.skip=true -Dmaven.compile.fork=true --file pom.xml
        
    - name: Archive artifacts for jar
      if: true
      uses: actions/upload-artifact@v4
      with:
          name: maven-resolver-ant-tasks-uber.indiff.${{ env.BUILD_VERSION_TIMESTAMP }}
          retention-days: 7 # 保留期 
          compression-level: 9 # 压缩级别
          path: |
            ./target/*.jar

    - name: Publish release
      run: |
        set -xe
        sudo apt-get install \
          zip \
          unzip
        sudo timedatectl set-timezone Asia/Shanghai
        export build_timestamp="$(date +'%Y%m%d_%H%M')"
        echo -e "> Automated release OpenSSH_${OPENSSHVER} with OpenSSL_${OPENSSLVER}.\n" > ${{ github.workspace }}/RELEASE.md
        cat <<'EOF' >> ${{ github.workspace }}/RELEASE.md
        # Proxy download:
        ```bash
        curl -#Lo openssh-indiff.zip "https://ghproxy.it/https://github.com/indiff/openssh-deb/releases/download/OpenSSH_shitver_shitstamp/openssh_resolute_26.04_shitstamp.x86_64.zip"
        ```
          
        # Direct download:
        ```bash         
        curl -#Lo openssh-indiff.zip "https://github.com/indiff/openssh-rpms/releases/download/OpenSSH_shitver_shitstamp/openssh_resolute_26.04_shitstamp.x86_64.zip"
        ```

        ```
        ls -l *.deb
        sudo dpkg -i *.deb
        ```
        ```
        cat << 'EOF' > /etc/ssh/sshd_config
        Port 22
        AddressFamily inet
        PubkeyAcceptedAlgorithms +ssh-rsa
        PermitRootLogin yes
        PasswordAuthentication yes
        UseDNS no
        UsePAM yes
        TCPKeepAlive yes
        ClientAliveInterval 60
        ClientAliveCountMax 3
        #Subsystem sftp  internal-sftp
        Subsystem sftp  /usr/libexec/openssh/sftp-server
        KexAlgorithms -diffie-hellman-group1-sha1,diffie-hellman-group1-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group15-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha256,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha512
        shitshit
        ```
        EOF
        sed -i "s/shitver/${OPENSSHVER}/g" RELEASE.md
        sed -i "s/shitstamp/${build_timestamp}/g" RELEASE.md
        sed -i 's/shitshit/EOF/g' RELEASE.md
        GITHUB_REF=${{ github.ref }}
        TAGNAME="maven-resolver-ant-tasks_${build_timestamp}"
        NAME="${TAGNAME}"
        git tag -l --format='%(contents)' "${TAGNAME}" | tee -a ${{ github.workspace }}/RELEASE.md
        gh release delete --cleanup-tag --yes "$TAGNAME" || true
        gh release create "$TAGNAME" --target "master" -F ${{ github.workspace }}/RELEASE.md --title "$NAME" ./target/*.jar

    - name: Check Version with Maven
      run: mvn -U -B -T 1C versions:display-dependency-updates "-Dmaven.version.ignore=.*android.*" -Dmaven.test.skip=true -Dmaven.compile.fork=true --file pom.xml
